### ISSUE TITLE
Can't understand how vidOffset works

### ISSUE THREAD

**Issue by akritiko** [HubSpot/hubspot-php#115]
I tried using the vidOffset property but anything I put as a value doesn't seem to have any effect to the response. Tested it with contact per the example on the README of the repo.

**Comment by maddy2101** [comment]
you receive the offset value with each response (e.g from the allContacts endpoint). To get all contacts, you need a while loop, that runs as long as the response has the hasMore value set to true. With the next request, you pass the offset you received from the former response as a parameter.

example:
$requestParams = [
  'limit' => 75,
  'properties' => 'firstname', 'lastname',
];
$offset = 0;
$hasMore = true;
while ($hasMore === true) {
  $response = $contacts->all($requestParams + ['offset => $offset];
  foreach ($response['contacts'] as $contact) {
    // whatever you do here ....
  }
  $offset = $response['vid-offset'];
  $hasMore = $response['hasMore'];
}

take note, this is written from memory, but you should be able to figure it out.

**Comment by ksvirkou-hubspot** [comment]
Hi @akritiko 
Workable example (SDK v4.0.2)
```php
$hubspot = Factory::createWithOAuth2Token(
    '*', 
    null,
    ['http_errors' => false]
);
$offset = null;
do {
    $params = ['count' => 100];
    if (!empty($offset)) {
        $params['vidOffset'] = $response->{'vid-offset'};
    }
    $response = $hubspot->contacts()->all($params)->getData();

    var_dump($response->{'has-more'}, $response->{'vid-offset'});

    $offset = $response->{'vid-offset'};
} while ($response->{'has-more'} === true);
```
