### ISSUE TITLE
Soft reserved word Resource

### ISSUE THREAD

**Issue by wilsonpinto** [HubSpot/hubspot-php#120]
As we can check here [http://php.net/manual/en/reserved.other-reserved-words.php](http://php.net/manual/en/reserved.other-reserved-words.php) Resource may be used in the future as reserved word. Would be useful if i create a PR with naming changes to be applied on version 2.0 ? If yes, let me know what would be the proper naming.

Thanks.

**Comment by ryanwinchester** [comment]
Maybe we could change `Resource` to `Endpoint`

**Comment by ksvirkou-hubspot** [comment]
`Endpoint` will be good
@wilsonpinto 
if you create a PR I'll review and merge it

**Comment by wilsonpinto** [comment]
@ksvirkou-hubspot done
