### ISSUE TITLE
How to update a contact's properties?

### ISSUE THREAD

**Issue by aacook** [HubSpot/hubspot-php#125]
This is less of an issue and more of a general question.

How would I update/set a custom property on a contact?

**Comment by tallcoder** [comment]
@aacook This is what I'm working on now. If I get it figured out I will reply back on here. 👍

**Comment by maddy2101** [comment]
- you need the id of the contact record
- you put up an array containing the properties and values as required by the API with your desired fields
- you post the changes using the contact update endpoint.

**Comment by benblub** [comment]
```php
$proberties = array("firstname" => 'Foo');
        $client = new Client([
            'key' => self::HAPI_KEY
        ]);
        $contacts = new Contacts($client);
        $result = $contacts->update($user->getHubspotContactId(), $proberties);
```

got error
HTTP/1.1 400 Bad Request
Date: Wed, 07 Feb 2018 11:56:42 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked

**Comment by benblub** [comment]
Testing without this wrapper i got following

```php
        $postData = array('firstname' => 'Foo');
        // Setup cURL
        $ch = curl_init('https://api.hubapi.com/contacts/v1/contact/vid/'.$teilnehmer->getHubspotContactId().'/profile?hapikey='.self::HAPI_KEY);
        curl_setopt_array($ch, array(
            CURLOPT_POST => true,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER => array(
                'Authorization: '.self::HAPI_KEY,
                'Content-Type: application/json'
            ),
            CURLOPT_POSTFIELDS => json_encode($postData)
        ));

        // Send the request
        $response = curl_exec($ch);

        // Check for errors
        if ($response === false) {
            die(curl_error($ch));
        }

        // Decode the response
        $responseData = json_decode($response, true);

        dump($responseData);
```

  "status" => "error"
  "message" => "Json node is missing child properties"
  "correlationId" => "f86b988e-b109-4e97-be98-e68e3166c185"
  "requestId" => "9c520d1930d76670cbaa1856766f52d3"

**Comment by benblub** [comment]
createOrUpdate a contact example @aacook 

```php
        $client = new Client(['key' => $this->hapyKey]);
        $contacts = new Contacts($client);
$result = $contacts->createOrUpdate($email, array(
            ['property' => 'firstname', 'value' => 'foo'],
            ['property' => 'lastname', 'value' => 'bar'],
        ));
```

**Comment by mmickelson** [comment]
I have this question too. There is a quick example of getting a contact property but not one for updating a property. I can't tell if the above comments are supposed to be examples of how to do it or questions...

**Comment by ksvirkou** [comment]
Hi @aacook  
you can change it
$hubSpot->contactProperties()->update($name, $propertyFields);
or 
Factory::create(getenv('HUBSPOT_TEST_API_KEY'))->objectProperties('products')->update('customprop', [
            'label' => 'Custom property',
            'description' => 'An Awesome Custom property',
            'groupName' => $this->groupName,
            'type' => 'string',
            'fieldType' => 'text',
            'formField' => true,
            'displayOrder' => 6,
            'options' => [],
        ]);
Also You can check [our sample apps](https://github.com/HubSpot/integration-examples-php)
