### ISSUE TITLE
Create timeline event by API

### ISSUE THREAD

**Issue by gtulga** [HubSpot/hubspot-php#129]
Hi,

I'm trying to log our server event in contact's timeline. I'm planning to use Timeline API, but it requires access token. My implementation requires server to API endpoint, but Timeline API access token looks like only work browser to API endpoint. am I right? or not?

How to create event from server to contact's timeline?

Thanks,

**Comment by jideokus** [comment]
Hi @gtulga. I was just able to implement this yesterday. I did this by using OAuth2. I set up an initial connection with my HubSpot instance to my HubSpot app. There's some documentation on how to do this here
https://developers.hubspot.com/docs/methods/oauth2/initiate-oauth-integration
After the inial connection, an access token and a refresh token will be returned.
https://developers.hubspot.com/docs/methods/oauth2/get-access-and-refresh-tokens

What I did was to store those in my database and use the access key to make any API call, including timeline calls.

Something to note about the access token is that they expire after 6 hours, so you will need the refresh token to get a new one when it does
https://developers.hubspot.com/docs/methods/oauth2/refresh-access-token

I had to reimplement with OAuth2 just to use this feature but it makes using the API a lot easier as well.

**Comment by mikeamcbrien** [comment]
@jideokus Would you be willing to give more information or preferably example code on how you did the Oauth2 and how you are refreshing the token?

I am running into the same hurdle right now.

**Comment by monmonja** [comment]
incase you are running into this to get the code do something (this is in laravel)
```
public function hubspotLogin (Request $request) {
  $clientId = getenv('HUBSPOT_APP_CLIENT_ID');
  $scope = 'timeline';  
  $redirectUri = getenv('HUBSPOT_APP_REDIRECT_URI');  
  $url = "https://app.hubspot.com/oauth/authorize?client_id={$clientId}&scope={$scope}&redirect_uri={$redirectUri}";  
  return Redirect::to($url);
}
```
then put this on any class
```
public static function refreshToken ($code, $grantType='refresh_token') {
        $client = new Client([
            'base_uri' => 'https://api.hubapi.com/oauth/v1/token',
            'timeout'  => 2.0,
        ]);

        $response = $client->post('https://api.hubapi.com/oauth/v1/token', [
            'form_params' => [
                'grant_type' => $grantType,
                'client_id' => getenv('HUBSPOT_APP_CLIENT_ID'),
                'client_secret' => getenv('HUBSPOT_APP_CLIENT_SECRET'),
                'redirect_uri' => getenv('HUBSPOT_APP_REDIRECT_URI'),
                'code' => $code
            ],
        ]);
        return (string) $response->getBody();
}
```
on your redirect uri route, save the results to db
```
 HubspotApi::refreshToken($request->get('code'), 'authorization_code');
```

**Comment by ksvirkou** [comment]
Hi everyone 
We have [timeline sample app](https://github.com/HubSpot/integration-examples-php)
[getting OAuth token](https://github.com/HubSpot/integration-examples-php/blob/master/timeline-app/src/Helpers/Oauth2Helper.php)
We got a token and keep it db
[sending event](https://github.com/HubSpot/integration-examples-php/blob/master/timeline-app/src/Helpers/TimelineEventHelper.php)

**Comment by ksvirkou** [comment]
Hi everyone @gtulga @jideokus @mikeamcbrien @monmonja 
we have [timeline sample app](https://github.com/HubSpot/integration-examples-php)
[I get token and save it in db ](https://github.com/HubSpot/integration-examples-php/blob/master/timeline-app/src/Helpers/Oauth2Helper.php)
[Sending events](https://github.com/HubSpot/integration-examples-php/blob/master/timeline-app/src/Helpers/TimelineEventHelper.php)
