### ISSUE TITLE
Batch Update Companies

### ISSUE THREAD

**Issue by RobDesilets** [HubSpot/hubspot-php#137]
Hi,

First of all, great API!

I have the need to batch update companies in the overnight hours. 

I tried to find the implementation of this in your API:

https://developers.hubspot.com/docs/methods/companies/batch-update-companies

... and I can't .. is it something you might be able to add?

**Comment by beinbm** [comment]
will be solved with https://github.com/ryanwinchester/hubspot-php/pull/138

**Comment by ksvirkou** [comment]
All ready implemented
