### ISSUE TITLE
Request response when caught BadResponseException

### ISSUE THREAD

**Issue by phena109** [HubSpot/hubspot-php#143]
Hi Ryan,

I am using `SevenShores\Hubspot\Resources\Contacts::create()` and when a contact already exist the server throws me a 409 Conflict response. The response I got from catching the exception, however, is somewhat a not-so-friendly string. `$e->getMessage()` gets me the whole http response in string format (headers + body) rather than just the body which is usually a JSON string and so much easier to parse for further use.

Digging in the code, I can see that `SevenShores\Hubspot\Http\Client::request()` handles the exception first hand and throw another `SevenShores\Hubspot\Exceptions\BadRequest` exception based on what caught in the first place.

In most of the case this is fine, but there are times (like the case above) I really need the content of the response to move on with what I am doing. A better representation of the error rather than work around that by parsing the exception message will certainly help.

For now a parser library to parse the exception message should get me going but this is really redundant. If this should be changed, can you suggest a direction to go so we maybe able to create a PR for that or better can you please update so the exceptions thrown can be more user friendly?

Thanks,
D

**Comment by nerdstein** [comment]
+1 on this request. It would be really helpful to have some documentation on debugging requests.

**Comment by jamesgraham** [comment]
+1 we have a similar problem- the Hubspot\Exceptions\BadRequest just gives a raw response.

```SevenShores\Hubspot\Exceptions\BadRequest
HTTP/1.1 401 Unauthorized
Date: Fri, 01 Jun 2018 17:55:24 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 327
Connection: keep-alive
Set-Cookie: __cfduid=xxx; expires=Sat, 01-Jun-19 17:55:24 GMT; path=/; domain=.hubapi.com; HttpOnly
Access-Control-Allow-Credentials: false
X-Trace: 2BAAEB01B4DC039F459420827F7C98211810CEFF68000000000000000000
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 42438d0e9bdd572f-IAD

{"status":"error","message":"This oauth-token (aaa-bbb) is expired! expiresAt: 1527875724384, now: 1527875724575","correlationId":"e02e284a-f360-4351-baf1-82a132631b63","requestId":"xx"}
```

It would be great to map http error codes to specific exceptions, and then access the payload as properties

**Comment by mordonez** [comment]
Perhaps using the previous Exception (Guzzle) can helps, something like that:

```
try {
       // do stuff
    } catch (\SevenShores\Hubspot\Exceptions\BadRequest $ex) {
        $guzzleException = $ex->getPrevious();
        $error = json_decode((string)$guzzleException->getResponse()->getBody());
        // now error is mapped with the response
 }
```

**Comment by atymic** [comment]
I'll make a PR for this shortly :)

**Comment by ksvirkou-hubspot** [comment]
Hi Everyone 
The easiest way to get the original error message 
```php
$hubspot = Factory::createWithOAuth2Token(
    '*',
    null,
    ['http_errors' => false] // pass any Guzzle related option to any request, e.g. throw no exceptions
);

$properties = [
    [
        'property' => 'email',
        'value' => 'apitest@hubspot.com',
    ],
    [
        'property' => 'firstname',
        'value' => 'hubspot',
    ],
    [
        'property' => 'lastname',
        'value' => 'user',
    ],
    [
        'property' => 'phone',
        'value' => '555-1212',
    ],
];

$response = $hubspot->contacts()->create($properties);

var_dump($response->getData()->message);
```
