### ISSUE TITLE
Analytics API added by Hubspot

### ISSUE THREAD

**Issue by adrian-stein** [HubSpot/hubspot-php#148]
They have added an analytics endpoint. Any chance this will be added anytime soon?
https://developers.hubspot.com/docs/methods/analytics/analytics-overview

**Comment by adrian-stein** [comment]
They actually added 7 new ones, but im only interested in the one currently, but as an FYI. https://www.hubspot.com/product-updates/a-roundup-of-the-new-hubspot-apis

**Comment by hi0001234d** [comment]
Hello :-)

I'm also actually looking for Analytics API. Is there any plan to add it anytime sooner?

**Comment by adrian-stein** [comment]
Hey there. Is there any plans on building this in in the near future?

**Comment by pluckydukk** [comment]
Also looking for the Analytics API.  Hoping it can be done soon!

**Comment by thunder87** [comment]
I just submitted a [PR](https://github.com/ryanwinchester/hubspot-php/pull/174) for the analytics bit, waiting for it to be integrated.

**Comment by atanasiuk-hubspot** [comment]
[PR](https://github.com/HubSpot/hubspot-php/pull/174) is merged.
