### ISSUE TITLE
QUESTION: Contacts API Search Returns Incorrect Results

### ISSUE THREAD

**Issue by dainemedia** [HubSpot/hubspot-php#149]
Hey Folks,

I've posted this question on the HubSpot Developer forums, but got no response.

I'm using the Contact API Search endpoint and sending a query string. It returns a result and no errors, but no matter what query I send it always returns the exact same 19 results and they don't match the query a send.

Any ideas what I may be doing wrong, or whether there's a problem?

This is the code I'm using: `contacts()->search(request()->get('query'));`

**Comment by erikrorstrom** [comment]
@affinitycloud 
When i try it in postman it seems to work fine.

what does "has-more" and "total" say in the response you get? Are you just returning an empty search (all contacts)? 

If you dump out `request()->get('query')` are you getting your search-term?

**Comment by ksvirkou-hubspot** [comment]
I ve just check `contacts()->search()` 
it works fine
Probably it was cache
