### ISSUE TITLE
CampaignIds vs CampaignsById

### ISSUE THREAD

**Issue by JorisDebonnet** [HubSpot/hubspot-php#169]
Nice module! Just started using it, and was a little confused by the naming of the methods in the EmailEvents class. One of the API endpoints is not currently supported: [`/email/public/v1/campaigns/by-id`](https://developers.hubspot.com/docs/methods/email/get_campaigns_by_id). Not that I need it -- but I assumed that `EmailEvents::getCampaignIds` would actually be calling that. 

My suggestion: 
* Deprecate `EmailEvents::getCampaignIds`, rename it to `EmailEvents::getCampaigns`
* Introduce `EmailEvents::getCampaignsById` which calls `/email/public/v1/campaigns/by-id`

**Comment by ksvirkou** [comment]
Hi @JorisDebonnet 
it is already fixed 
[take a look(v2)](https://github.com/HubSpot/hubspot-php/releases/tag/v2.0.0)
