### ISSUE TITLE
pipelines

### ISSUE THREAD

**Issue by JorisDebonnet** [HubSpot/hubspot-php#170]
The Deal Pipelines API is deprecated. 
https://developers.hubspot.com/docs/methods/deal-pipelines/overview

Could you please add support for the recommended alternative: CRM pipelines? The output is extremely similar but not quite exactly the same,.. so I'm afraid it may need a separate class. 
https://developers.hubspot.com/docs/methods/pipelines/pipelines_overview

**Comment by annamasc** [comment]
What is the status of this issue?
