### ISSUE TITLE
eCommerce Integration

### ISSUE THREAD

**Issue by shabananavas** [HubSpot/hubspot-php#180]
The product and line item resources should be added as well.

**Comment by audetcameron** [comment]
Is lineItems completely gone?  I had it in 1.0
`
namespace SevenShores\Hubspot\Resources;

use SevenShores\Hubspot\Exceptions\HubspotException;

class LineItems extends Resource {
    /**
     * @param array $line_item Array of deal properties.
     * @return mixed
     * @throws HubSpotException
     */
    function create(array $line_item)
    {
        $endpoint = "https://api.hubapi.com/crm-objects/v1/objects/line_items";

        $options['json'] = $line_item;

        return $this->client->request('post', $endpoint, $options);
    }
}

`

**Comment by shabananavas** [comment]
It's not in the latest 1.1.3, unless I'm missing something.

**Comment by audetcameron** [comment]
You are correct, product is missing as well.

**Comment by shabananavas** [comment]
I've now looked through pretty much all the releases and none of them have the Product or LineItem Resources. If it doesn't exist, then, we could start work on it.

**Comment by shabananavas** [comment]
Added a start here:

https://github.com/shabananavas/hubspot-php/pull/1

**Comment by ksvirkou** [comment]
Hi @shabananavas @audetcameron 
Products API is already done 
LineItem I will do tomorrow

**Comment by shabananavas** [comment]
Thanks @ksvirkou! Appreciate it.

**Comment by audetcameron** [comment]
> Hi @shabananavas @audetcameron
> Products API is already done
> LineItem I will do tomorrow

very nice.

**Comment by ksvirkou** [comment]
https://github.com/HubSpot/hubspot-php/pull/287

**Comment by ksvirkou** [comment]
Hi  @shabananavas and @audetcameron
Products and LineItem API are already done 
But for using it you have to it update to v2.0.3
if you have any questions create a new issue
