### ISSUE TITLE
Associate CRM objects

### ISSUE THREAD

**Issue by shabananavas** [HubSpot/hubspot-php#181]
Create a resource to allow associations like a line item to a deal, etc.

**Comment by domagoj03** [comment]
Hello @shabananavas,
there's already a way to do this, however I think it's not documented.
Try it with `Resource/CrmAssociations` class. However, as I can see, not all endpoints are implemented, like for example batch update.

**Comment by shabananavas** [comment]
Thanks @domagoj03, I'll look into that.
