### ISSUE TITLE
Complete Example to create a history event with Oauth2

### ISSUE THREAD

**Issue by stephanraabe74** [HubSpot/hubspot-php#193]
Hi,

I have tested this API with simple contact requests and it works very well. Now I want to create events on the contact timelines. App is created, refresh token is available.

Can you provide a complete running example about how to create a timeline event with Oauth authorization by using the refresh key included?

Thank you for your help,

Stephan

**Comment by ksvirkou** [comment]
Hi @stephanraabe74 
Yes can find it [here](https://github.com/HubSpot/integration-examples-php)
