### ISSUE TITLE
Cant create new contact

### ISSUE THREAD

**Issue by anushkanz** [HubSpot/hubspot-php#195]
$leadid = $request->all()['leadid'];
        $firstname = $request->all()['firstname'];
        $lastname = $request->all()['lastname'];
        $email = $request->all()['email'];
        $phone = $request->all()['phone'];

        //Get User Id
        $userid = Auth::User()->id;

        //Get User Group Id
        $getGroupUser = Groupuser::where('userId', $userid)->get()->toArray();
        $getGroupId = $getGroupUser['0']['groupId'];

        //Get Group Details
        $getGroup = Group::where('id', $getGroupId)->get()->toArray();

        //Get Hubspot API
        $hubspotApi =  $getGroup[0]['hubspotApi'];

        $client = new Client(['key' => $hubspotApi]);

        //Hubspot array
        $hubspotarray = array(
            'properties' => array(
                array(
                    'property' => 'email',
                    'value' => $email
                ),
                array(
                    'property' => 'firstname',
                    'value' => $firstname
                ),
                array(
                    'property' => 'lastname',
                    'value' => $lastname
                ),
                array(
                    'property' => 'phone',
                    'value' => $phone
                )
            )
        );

        $hubspot = new Contacts($hubspotconnection);
        $response = $hubspot->create($hubspotarray);

        print_r($response);
 This is response i got
SevenShores \ Hubspot \ Exceptions \ BadRequest (400)
HTTP/1.1 400 Bad Request Date: Tue, 04 Jun 2019 21:57:25 GMT Content-Type: application/json;charset=utf-8 Transfer-Encoding: chunked Connection: keep-alive Set-Cookie: __cfduid=d592ae52e4275679c85da662ad1a39c491559685445; expires=Wed, 03-Jun-20 21:57:25 GMT; path=/; domain=.hubapi.com; HttpOnly X-Trace: 2B5F124878F94494C7D417430C56F777AECF30C490000000000000000000 X-HubSpot-RateLimit-Daily: 40000 X-HubSpot-RateLimit-Daily-Remaining: 39990 X-HubSpot-RateLimit-Secondly: 10 X-HubSpot-RateLimit-Secondly-Remaining: 9 Vary: Accept-Encoding, Accept-Encoding Access-Control-Allow-Credentials: false Strict-Transport-Security: max-age=31536000; includeSubDomains; preload Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" Server: cloudflare CF-RAY: 4e1d2990499b190c-AKL {"status":"error","message":"property cannot be missing or null","correlationId":"ed5e5aba-6c67-468d-9018-fe2fb122450a","requestId":"ee68a5269624140c5742db0a70044881"}

 Please help me to sort this issue.
Thanks

**Comment by johnhearfield** [comment]
This is the Contacts resource:
```
    function create($properties)
    {
        $endpoint = "https://api.hubapi.com/contacts/v1/contact";

        $options['json'] = ['properties' => $properties];

        return $this->client->request('post', $endpoint, $options);
    }
```
It seems that is already sets the `properties` array for you, so you just need to remove the `properties` inner array from your `$hubspotarray`

**Comment by ksvirkou** [comment]
@anushkanz 
Regarding Resource creating
`new Contacts(new Client(['key' => getenv('HUBSPOT_TEST_API_KEY')]))`
no needed to set properties
for example 
`$properties = [];
    foreach ($contactProperties as $key => $value) {
        $properties[] = [
            'property' => $key,
            'value' => $value,
        ];
    }
    // https://developers.hubspot.com/docs/methods/contacts/create_or_update
    $createOrUpdateResponse = $hubSpot->contacts()->createOrUpdate($contactProperties['email'], $properties);`

Also - HubSpot published new repo with sample apps https://github.com/HubSpot/integration-examples-php - it demos varies calls, including contact create in contacts sample app https://github.com/HubSpot/integration-examples-php/tree/master/contacts-app
