### ISSUE TITLE
Products API

### ISSUE THREAD

**Issue by mewejo** [HubSpot/hubspot-php#196]
Can I please ask for the products API to be added? As per: https://developers.hubspot.com/docs/methods/products/products-overview

I would look into submitting a PR but looks like all the Travis tests are failing 👎

**Comment by craigcri** [comment]
I second this request. Would love to get a Products wrapper added.

**Comment by ksvirkou** [comment]
Hi @mewejo and @craigcri 
I am working on it 
It will be done in a few days

**Comment by ksvirkou** [comment]
https://github.com/HubSpot/hubspot-php/pull/283

**Comment by ksvirkou** [comment]
hey @mewejo and @craigcri
I've just merged it
I will release a version  in a few hours
