### ISSUE TITLE
Error getting form fields

### ISSUE THREAD

**Issue by veiss-com** [HubSpot/hubspot-php#197]
- **Library version:** 1.2.0
- **Error:** Attempted to load class "GetFields" from namespace "SevenShores\Hubspot\Resources". Did you forget a "use" statement for another namespace? 

Hello,

I recently added the library to a Symfony 2 project to handle form submissions.
I am able to get contacts and submit forms, but can't get the form fields.

I am getting the following error:

> Attempted to load class "GetFields" from namespace "SevenShores\Hubspot\Resources".
> Did you forget a "use" statement for another namespace? 

Weird, because I am able to submit forms.

Please, let me know if you need more info.

Thanks in advance.

**Comment by atymic** [comment]
`GetFields` isn't an api, it's a method on the forms API.
You are looking for the following code:
```php
$factory->forms()->getFields()
```

**Comment by ksvirkou-hubspot** [comment]
> `GetFields` isn't an api, it's a method on the forms API.
> You are looking for the following code:
> 
> ```
> $factory->forms()->getFields()
> ```

@veiss-com  ^^
@atymic is right 
getFields is an api method
