### ISSUE TITLE
Naming of methods getAll() vs all()

### ISSUE THREAD

**Issue by annamasc** [HubSpot/hubspot-php#200]
I was a little confused with the naming consistency of some of the methods, for example Contacts has the method all() and Deals has the method getAll(), but both methods have equivalent functionality... My suggestion would be to have a consistent naming convention throughout the module.

Otherwise, I'm very happy with this module :smile:

**Comment by ksvirkou** [comment]
Hi it is already done 
and available at [v2](https://github.com/HubSpot/hubspot-php/releases/tag/v2.0.0)
