### ISSUE TITLE
create a new contact?

### ISSUE THREAD

**Issue by rkflores** [HubSpot/hubspot-php#201]
how to create a new contact?

**Comment by alex-bukach** [comment]
$client = new SevenShores\Hubspot\Http\Client(['key' => 'my-key-here']);
    $contacts_api = new SevenShores\Hubspot\Resources\Contacts($client);
    $contacts_api->create($properties);

**Comment by yfaktor** [comment]
Also - HubSpot published new repo with sample apps https://github.com/HubSpot/integration-examples-php - it demos varies calls, including contact create in contacts sample app https://github.com/HubSpot/integration-examples-php/tree/master/contacts-app
