### ISSUE TITLE
Any support for v3 endpoints?

### ISSUE THREAD

**Issue by audetcameron** [HubSpot/hubspot-php#207]
First: Great package, been using it for over a year now. Thanks for the hard work.

New Hubspot GDPR endpoints are v3, https://developers.hubspot.com/docs/methods/forms/submit_form_v3

Any way to change the endpoint per request?

//maybe like a 

 ```
function submit($portal_id, $form_guid, $form, $version='v2')
    {
        switch (strtolower ($version)) {
               case 'v3':
                $endpoint = "https://api.hsforms.com/submissions/v3/integration/submit/{$portal_id}/{$form_guid}";
                 break;           
             default:
                $endpoint = "https://forms.hubspot.com/uploads/form/v2/{$portal_id}/{$form_guid}";
                 break;
         } 

        $options['form_params'] = $form;

        return $this->client->request('post', $endpoint, $options, null, false);
    }

```

**Comment by adriadrop** [comment]
Most are using v1, so this package is a bit outdated.

**Comment by ryanwinchester** [comment]
HubSpot is taking over the library.

**Comment by audetcameron** [comment]
> HubSpot is taking over the library.

for real?  That must feel pretty good eh?

**Comment by ryanwinchester** [comment]
> for real? That must feel pretty good eh?

Yeah, it's good since it seems the library seems to get a lot of use and I don't have any bandwidth to maintain it lately. (Also, I haven't even touched PHP for work in years).

**Comment by umakantsharmacedcoss** [comment]
@ryanwinchester i would love to maintain this, and i think this is the good feature to start with - add v3 support.

**Comment by audetcameron** [comment]
> @ryanwinchester i would love to maintain this, and i think this is the good feature to start with - add v3 support.

The question would be if HubSpot plans to integrate v3 into this package or if they are hiring ;)

**Comment by ksvirkou** [comment]
Hi Everybody 
At this moment we support all v3 methods 
You can use it 
[take a look ](https://github.com/HubSpot/hubspot-php/releases/tag/v2.0.0)

**Comment by atanasiuk-hubspot** [comment]
This is correct, feel free to reopen or create a new issue if there are any questions.
