### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by massimilianobraglia** [HubSpot/hubspot-php#220]
Hey there, just a thought.
Is this library interested in dropping support to PHP < 7?
In this way it is possible to refactor a lot of code and improve it

**Comment by atanasiuk-hubspot** [comment]
Hi, @massimilianobraglia  
Indeed, we are planning do drop support for PHP 5.* in the nearest future.

**Comment by massimilianobraglia** [comment]
hey @atanasiuk-hubspot, thanks for your answer.
If you want I can create some PRs in order to help the migration

**Comment by atanasiuk-hubspot** [comment]
Close it until PHP 5.* is dropped
