### ISSUE TITLE
Missing crmPipelines Factory method

### ISSUE THREAD

**Issue by trombini77** [HubSpot/hubspot-php#247]
I didn´t find the following line in the /Utils/Factory.php:

* @method \SevenShores\Hubspot\Resources\CrmPipelines     crmPipelines()

and the * @method \SevenShores\Hubspot\Resources\DealPipelines     dealPipelines() is deprecated as possible to check in https://developers.hubspot.com/docs/methods/deal-pipelines/overview

**Comment by atymic** [comment]
Fixed in https://github.com/HubSpot/hubspot-php/pull/277
