### ISSUE TITLE
Deal's create method without properties produces error

### ISSUE THREAD

**Issue by amancho** [HubSpot/hubspot-php#254]
Some "objects" (Contacts, Tickets, etc) are created using a POST request with a property called "properties" in your body data. It's the default aprox. in oficial documentation. 

In deal's create method not exists, by default, the property called "properties" and produces an error.

Why remove the property "properties" in Deal's create method?
It's for some particular reason?

Thanks.

src/Resources/Contacts.php
Contact's create method

```
/**
* @param array $properties Array of contact properties.
* @return \SevenShores\Hubspot\Http\Response
*/
    function create($properties)
    {
        $endpoint = "https://api.hubapi.com/contacts/v1/contact";
        $options['json'] = ['properties' => $properties];

        return $this->client->request('post', $endpoint, $options);
    }
```

src/Resources/Deals.php
Deal's create method
```
/**
     * @param array $deal Array of deal properties.
     * @return mixed
     * @throws HubSpotException
     */
    function create(array $deal)
    {
        $endpoint = "https://api.hubapi.com/deals/v1/deal";
        $options['json'] = $deal;

        return $this->client->request('post', $endpoint, $options);
    }
```

**Comment by atymic** [comment]
The reason for this is because the API also takes an `associations` property.
Imo this method should have two params, but it doesn't and changing it would break BC.

https://developers.hubspot.com/docs/methods/deals/create_deal

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-php/pull/332
