### ISSUE TITLE
HubDB::addRow() Does not support 'name' and 'path' values for tables used for Dynamic Pages

### ISSUE THREAD

**Issue by RowanReid** [HubSpot/hubspot-php#281]
There is currently no way to pass through the values for 'name' and 'path' for HubDB Dynamic Pages table rows.

A fix would include updating line 209 in HubDB.php to include the values, e.g:

`['json' => ['values' => $values, 'path' => 'xxxx', 'name' => 'yyyy']]`

**Comment by ksvirkou** [comment]
@RowanReid added
