### ISSUE TITLE
Properties creating a Contact

### ISSUE THREAD

**Issue by ezequielprieto** [HubSpot/hubspot-php#292]
Hi everybody!
I'm having a problem creating a new Contact with the properties:
e.g.
$data = [
            [
                "name" => "email",
                "value" => $this->user->email,
            ],
            [
                "name" => "firstname",
                "value" => $this->user->first,
            ],
            [
                "name" => "lastname",
                "value" => $this->user->last,
            ],
            [
                "name" => "company",
                "value" => $this->company->name,
            ],
            [
                "name" => "website",
                "value" => $this->company->website,
            ],
            [
                "name" => "phone",
                "value" => $this->user->phone,
            ],            
            [
                "name" => "address",
                "value" => $this->user->address,
            ],            
            [
                "name" => "city",
                "value" => $this->user->city,
            ],            
            [
                "name" => "country",
                "value" => $this->company->country->nicename,
            ],            
            [
                "name" => "zip",
                "value" => $this->company->zip,
            ],            
            [
                "name" => "hubspot_owner_id",
                "value" => 123123123,
            ],            
            [
                "name" => "lifecyclestage",
                "value" => "lead",
            ],
        ];
$contact = $hubspot->contacts()->create($data);

**Response:**
response: {"status":"error","message":"property cannot be missing or null" (…)

Any idea?

**Comment by ksvirkou** [comment]
Hi @ezequielprieto 
There is two problem in your request 
1) incorrect format data. You have to replace name => property
E.g.
`$data = [
[
'property' => 'email',
'value' => $std->user->email,
],
];`
2) There is you have to specify a real id in 'hubspot_owner_id'  ( `$hubSpot->owners()->all()` )

 
Also You can check [Sample Apps](https://github.com/HubSpot/integration-examples-php)
Correct Example 
`$hubspot = HubspotClientHelper::createFactory();

$ownerId = $hubspot->owners()->all()->getData()[0]->ownerId;

$std = new stdClass();
$std->user = new stdClass();
$std->company = new stdClass();
$std->company->country = new stdClass();
$std->user->email  = 'kuzma'.uniqid().'@hubspot.com';
$std->user->first = 'Kuzma';
$std->user->last = 'Smith';
$std->company->name = 'HubSpot';
$std->company->website = 'https://www.hubspot.com/';
$std->user->phone = '+1235813213455';
$std->user->address = '1010 10th Street';
$std->user->city = 'Santa Monica,';
$std->company->country->nicename = 'USA';
$std->company->zip = '1010';

$data = [
[
'property' => 'email',
'value' => $std->user->email,
],
[
'property' => 'firstname',
'value' => $std->user->first,
],
[
'property' => 'lastname',
'value' => $std->user->last,
],
[
'property' => 'company',
'value' => $std->company->name,
],
[
'property' => 'website',
'value' => $std->company->website,
],
[
'property' => 'phone',
'value' => $std->user->phone,
],
[
'property' => 'address',
'value' => $std->user->address,
],
[
'property' => 'city',
'value' => $std->user->city,
],
[
'property' => 'country',
'value' => $std->company->country->nicename,
],
[
'property' => 'zip',
'value' => $std->company->zip,
],
[
'property' => 'hubspot_owner_id',
'value' => $ownerId,
],
[
'property' => 'lifecyclestage',
'value' => 'lead',
],
];
$contact = $hubspot->contacts()->create($data);
var_dump(
        $contact->getStatusCode(),
        $contact->getReasonPhrase()
        ); exit();`

Best Regards and Happy HubSpotting,
Kuzma

**Comment by ezequielprieto** [comment]
> incorrect format data. You have to replace name => property

That was the problem!! Thanks! 🙏🏻
