### ISSUE TITLE
Update Deals Endpoints / API to V3

### ISSUE THREAD

**Issue by omacranger** [HubSpot/hubspot-php#293]
With the migration to some of the newer endpoints, I noticed the deals are still using the old endpoints, `v1`. I have a fork of this I'm working with which has some of the endpoints / documentation updated to handle the new endpoints (specifically, batch creation of deals). I'd be more than happy to put a PR together if you aren't already working on the feature.

**Comment by cincauhangus** [comment]
they already have but in a different repo: https://github.com/HubSpot/hubspot-api-php

**Comment by omacranger** [comment]
Interesting. Thanks. I'll take a look at it.

**Comment by ksvirkou-hubspot** [comment]
@omacranger 
We are developing [v3](https://github.com/HubSpot/hubspot-api-php)
If you have any questions, feel free to contact me
