### ISSUE TITLE
CRM Search (v3) support

### ISSUE THREAD

**Issue by jamesgraham** [HubSpot/hubspot-php#294]
We noted with dissapointment that it is not possible to search for a company other than by domain.

It looks like a new v3 API supports this: https://developers.hubspot.com/docs-beta/crm/search

Are there any immediate plans to add support for these endpoints?

**Comment by yfaktor** [comment]
hi @jamesgraham  - we are publishing new SDK for v3 version - it is in public beta already, here is the repo https://github.com/HubSpot/hubspot-api-php and the package is coming shortly . Hope it helps.

**Comment by yfaktor** [comment]
closing as per previous comment, pl feel free to reopen
