### ISSUE TITLE
Creating new Deal Pipelines fails

### ISSUE THREAD

**Issue by cincauhangus** [HubSpot/hubspot-php#295]
Previously I was able to create a new deal pipeline with stages that have upper case. Today however I'm unable to do so with hubspot returning this error:

```
{"status":"error","message":"Property name must be lowercase, but given: hs_date_entered_pipet
est2_all_stage_01A","correlationId":"0ffd7cd1-e74c-463d-81ff-6a51df956635","requestId":"26fc1144-f7a4-415d-b4bd-b522333885d
d"}
```

My pipeline contains stages like `pipetest2_all_stage_01A`. Seems like this is recently added as a Hubspot generated field.

Endpoint: https://api.hubapi.com/crm-pipelines/v1/pipelines/deals

**Comment by cincauhangus** [comment]
workaround: lower case stage_ids resolves this issue.

is it possible to update the [documentation](https://developers.hubspot.com/docs/methods/pipelines/create_new_pipeline) to reflect this recent change?

**Comment by zman81988** [comment]
Hi @cincauhangus I have updated the documentation to reflect the requirements for lower-casing the stage IDs.  Thanks for bringing this to our attention.

**Comment by cincauhangus** [comment]
@zman81988 I have existing stage IDs in upper case - created before this recent change, and so far I have no issues with it. I am wondering if there would be issues later down the road with existing IDs with upper case characters?
