### ISSUE TITLE
Freeze Guzzle to 6.5.0 until the intl issue has been remedied?

### ISSUE THREAD

**Issue by lesaff** [HubSpot/hubspot-php#296]
When running `hubspot-php` with the latest Guzzle (6.5.2), I get this error
`Call to undefined function GuzzleHttp\_idn_uri_convert()`

This is related to https://github.com/guzzle/guzzle/issues/2511

Perhaps Guzzle requirement in the composer should be locked to `6.5.0` for the time being until the issue has been remedied?

What do you think?

**Comment by jay-oswald** [comment]
I tried rolling back to `6.5.0` from `6.5.2` and it changed my `_idn_uri_covert()` error to `Uncaught Error: Call to undefined function GuzzleHttp\Psr7\get_message_body_summary()`, so rolling back didn't fix it for me

**Comment by lesaff** [comment]
Mine works fine after rolling back to `6.5.0`
Have you tried clearing your autoload to flush composer cache?

**Comment by jay-oswald** [comment]
I ended up finding the issue, another 3rd party a previous developer had used and that thing was using guzzle directly, not through composer, it was using version `6.3.x`, so autoloader was saying that the `functions.php` file so it didnt load the proper `functions.php` file, and the new version in the new files relied on functions that didnt used to exist, so was a conflict thing for me, from bad things a previous dev had done, and were burried in a different part of the project

**Comment by ksvirkou-hubspot** [comment]
@lesaff @jay-oswald 
I've just checked it 
it works fine for me 
guzzlehttp/guzzle 6.5.2

**Comment by lesaff** [comment]
@ksvirkou-hubspot Do you have `ext-intl` installed? I should probably add it for testing purpose.

This is what came up in the error
```
"suggest": { "psr/log": "Required for using the Log middleware", "ext-intl": "Required for Internationalized Domain Name (IDN) support" }
```

**Comment by ksvirkou-hubspot** [comment]
@lesaff no, I haven't

**Comment by ksvirkou-hubspot** [comment]
@lesaff have you already solved it?

**Comment by ksvirkou-hubspot** [comment]
@lesaff 
feel free to reopen
