### ISSUE TITLE
Retry on 502 Bad Gateway

### ISSUE THREAD

**Issue by gemal** [HubSpot/hubspot-php#315]
I use the latest version of the hubspot API and sometimes I experience the:

```
Error: Server error: PUT https://api.hubapi.com/companies/v2/companies/666666666?hapikey=*** resulted in a `502 Bad Gateway` response:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
```

would it be possible to have the retry middleware be able to retry such a situation?

**Comment by atanasiuk-hubspot** [comment]
This is what you might need:

```php
$handlerStack = \GuzzleHttp\HandlerStack::create();        
$handlerStack->push(
    \SevenShores\Hubspot\RetryMiddlewareFactory::createInternalErrorsMiddleware(
        \SevenShores\Hubspot\Delay::getExponentialDelayFunction(2)
    )
);
$guzzleClient = new \GuzzleHttp\Client(['handler' => $handlerStack]);

$config = [
    'key'      => 'demo',
    'oauth2'   => false,
];

$hubspot = new \SevenShores\Hubspot\Factory(config, new \SevenShores\Hubspot\Http\Client($config, guzzleClient));
```

**Comment by gemal** [comment]
according to the RetryMiddlewareFactory it seems to only do retry on 500 and 504 not 502

`return static::createMiddlewareByHttpCodeRange(500, 504, $delayFunction, $maxRetries);`

**Comment by gemal** [comment]
ahh sorry code range.. :)

**Comment by TimTheEnchanter** [comment]
> This is what you might need:
> 
> ```
> $handlerStack = \GuzzleHttp\HandlerStack::create();        
> $handlerStack->push(
>     \SevenShores\Hubspot\RetryMiddlewareFactory::createInternalErrorsMiddleware(
>         \SevenShores\Hubspot\Delay::getExponentialDelayFunction(2)
>     )
> );
> $guzzleClient = new \GuzzleHttp\Client(['handler' => $handlerStack]);
> 
> $config = [
>     'key'      => 'demo',
>     'oauth2'   => false,
> ];
> 
> $hubspot = new \SevenShores\Hubspot\Factory(config, new \SevenShores\Hubspot\Http\Client($config, guzzleClient));
> ```

Have a similar issue to the OP here.....was wondering where to implement that code.
