### ISSUE TITLE
Inconsistencies between Resources

### ISSUE THREAD

**Issue by marcorivm** [HubSpot/hubspot-php#319]
So for example when calling the update methods on Contacts, the updated properties will get wrapped on an array with a properties key
https://github.com/HubSpot/hubspot-php/blob/0c191a17739b280c36972ea72c790819bf0c1d9c/src/Resources/Contacts.php#L47

But when trying to update a Deal it expects the payload to already include the properties key
https://github.com/HubSpot/hubspot-php/blob/0c191a17739b280c36972ea72c790819bf0c1d9c/src/Resources/Deals.php#L40

**Comment by ksvirkou-hubspot** [comment]
it will be fix in the next major version

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-php/pull/332
