### ISSUE TITLE
Loosen Guzzle 7 constraint

### ISSUE THREAD

**Issue by Mosnar** [HubSpot/hubspot-php#336]
Version 3 now requires Guzzle 7; however, this has proven to be an issue since Guzzle 7 isn't widely adopted yet. Adding this requirement makes installing the SDK alongside many CMS impossible since allowing Guzzle 7 would be a large breaking change on their end.

The only benefit to Guzzle 7 as far as I can tell is that it supports PHP 8, which is not even released yet. My guess is that this library could safely allow Guzzle 6 and 7 simultaneously given the simplicity of what it's actually doing.

**Comment by ksvirkou-hubspot** [comment]
Could you check the latest version of the SDK please
@Mosnar
