### ISSUE TITLE
Retry on 524

### ISSUE THREAD

**Issue by gemal** [HubSpot/hubspot-php#341]
when I tried to use the API I got:
```
Error: Server error: `PUT https://api.hubapi.com/companies/v2/companies/666?hapikey=***` resulted in a `524 Origin Time-out` response:
<html>
<head><title>524 Origin Time-out</title></head>
<body bgcolor="white">
<center><h1>524 Origin Time-out</h1></c (truncated...)
```

Would it be possible to make the RetryMiddlewareFactory also work on 524 errors?

**Comment by ksvirkou-hubspot** [comment]
Hi @gemal 
Could you check this sample app?
https://github.com/HubSpot/integration-examples-php/tree/master/retry-middleware-app

**Comment by ksvirkou-hubspot** [comment]
RetryMiddlewareFactory::createMiddlewareByHttpCodes([524], Delay::getConstantDelayFunction())
