### ISSUE TITLE
Files - Replace method

### ISSUE THREAD

**Issue by Wardy195** [HubSpot/hubspot-php#345]
Seems the method here might be out of date. The old v2 URL giving a 404 error.

**Comment by ksvirkou-hubspot** [comment]
Hi @Wardy195  
check [this version (v3)](https://github.com/HubSpot/hubspot-php/releases/tag/v3.0.1) or [v2](https://github.com/HubSpot/hubspot-php/releases/tag/v2.0.7) please

It was fixed
