### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by nicobraintly** [HubSpot/hubspot-php#354]
Hello!

I see that you have bumped the version in composer.json to 3.1.0 after the merge of this PR https://github.com/HubSpot/hubspot-php/pull/351.

But no new release was made, so there is no way to install that version without using a commit tag or a branch. Am i missing something? is the release 3.1.0 scheduled? The last release tag i see is  "v3.0.1 - Fixed Files API + Guzzle 6 or 7"

Thanks!

@ksvirkou-hubspot

**Comment by ksvirkou-hubspot** [comment]
HI 
sorry fo delay
https://github.com/HubSpot/hubspot-php/releases/tag/3.1.0

**Comment by nicobraintly** [comment]
Thank you!
