### ISSUE TITLE
Is there a way to get all deals that are marked as 'closed won' that have been last modified within the past 5 days? 

### ISSUE THREAD

**Issue by michaelbarley** [HubSpot/hubspot-php#357]
In order to save on requests going forward, I need to only return deals that are closed won and that have been modified within the past 5 days. Is this possible? Thanks

**Comment by rodjsta** [comment]
Hi @michaelbarley, yes you can use the getRecentlyModified() method for deals using a 'since' query filter. You can then further filter those that are in the current stage of 'closed won' on your end with the results. 

Good luck.
