### ISSUE TITLE
Guzzle error

### ISSUE THREAD

**Issue by VencaKrecl** [HubSpot/hubspot-php#363]
This library is not compatible with guzzlehttp/guzzle ^7.3.0, see “Attempted to call function \“build_query\” from namespace \“GuzzleHttp\\Psr7\“.” The "build_query" function has been removed.

**Comment by ksvirkou-hubspot** [comment]
Hi 
check [this version](https://github.com/HubSpot/hubspot-api-php/releases/tag/5.0.0) please

**Comment by ksvirkou-hubspot** [comment]
Hi 
Could you check [the latest version](https://github.com/HubSpot/hubspot-php/releases/tag/v4.0.0)
