### ISSUE TITLE
How to create ticket with associate email?

### ISSUE THREAD

**Issue by nitinupify** [HubSpot/hubspot-php#380]
Hello
I want to create ticket using email and that ticket will display in particular user.
Also I want to add custom properties value in ticket. How can I do that?

**Comment by BatunaAz** [comment]
i can not create ticket too. 

passed array:
    $property = array();
    $property[0]['property'] = "hs_pipeline";
    $property[0]['value'] = "0";
    $property[1]['property'] = "hs_pipeline_stage";
    $property[1]['value'] = "1";
    $property[2]['property'] = "hubspot_owner_id";
    $property[2]['value'] = $owner[$ext];
    $property[3]['property'] = "subject";
    $property[3]['value'] = $number;
    $property[4]['property'] = "source_type";
    $property[4]['value'] = "PHONE";
Response: {"status":"error","message":"Cannot create object with type: TICKET. The following required properties were missing: [hs (truncated...)

i have no idea, why error occured,

**Comment by rodjsta** [comment]
@BatunaAz, it says it in your response. You're missing required params.

**Comment by BatunaAz** [comment]
if i use node API it works for passed params. Only PHP packages return this error.

**Comment by ksvirkou-hubspot** [comment]
Hi @BatunaAz 
for me it works correctly with your properties
```php
$hubspot = Factory::createWithOAuth2Token('*');
$response = $hubspot->tickets()->create([
    [
        'name' => 'subject',
        'value' => 'Ticket api v2',
    ],
    [
        'name' => 'source_type',
        'value' => 'PHONE',
    ],
    [
        'name' => 'hubspot_owner_id',
        'value' => '*',
    ],
    [
        'name' => 'hs_pipeline',
        'value' => '0',
    ],
    [
        'name' => 'hs_pipeline_stage',
        'value' => '1',
    ],
]);
```

**Comment by ksvirkou-hubspot** [comment]
Hi @nitinupify 
you can create an custom property using [CRM Object Properties API](https://legacydocs.hubspot.com/docs/methods/crm-properties/crm-properties-overview)
```php
$hubspot = Factory::createWithOAuth2Token('*');
$response = $hubspot->objectProperties('tickets')->create($property)
```
you can create an ticket using [Tickets API](https://legacydocs.hubspot.com/docs/methods/tickets/tickets-overview)
```php
$hubspot = Factory::createWithOAuth2Token('*');
$response = $hubspot->tickets()->create($ticket)
```
