### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dakorpar** [HubSpot/hubspot-php#382]
Hi,
PHP 8.1 is out for a long time now and in master there's already code to solve deprecations...
https://github.com/HubSpot/hubspot-php/commit/dc06898f57f0000f3be2339a8dbc9ac4e7a35257
Would it be possible then to just release new version so we depend on it since depending on dev-master is not best idea.

**Comment by ksvirkou-hubspot** [comment]
Hi @dakorpar  
Could you check[ new version of SDK](https://packagist.org/packages/hubspot/hubspot-php#4.0.2)?
