### ISSUE TITLE
Support for GDPR DELETE Endpoint

### ISSUE THREAD

**Issue by georgesamy** [HubSpot/hubspot-php#396]
Hubspot Contacts API supports an endpoint **GDPR DELETE**, can be found here: https://developers.hubspot.com/docs/api/crm/contacts

I couldn't find it in the SDK [here ](https://github.com/HubSpot/hubspot-php/blob/master/src/Endpoints/Contacts.php)

Are there plans to support it? Will gladly provide a PR for it.

**Comment by ksvirkou-hubspot** [comment]
This library supports only [legacy API](https://legacydocs.hubspot.com/docs/overview)
This method exists in [new version](https://github.com/HubSpot/hubspot-api-php)

**Comment by georgesamy** [comment]
Got it, thanks!
