### ISSUE TITLE
Analytics::getType uses wrong parameter names for start and end Dates

### ISSUE THREAD

**Issue by sinlyu** [HubSpot/hubspot-php#402]
The [implementation](https://github.com/HubSpot/hubspot-php/blob/8e399eb62ade528a47d1e10d1f76f729d0761f65/src/Endpoints/Analytics.php#L51) of [Get analytics data breakdowns](https://legacydocs.hubspot.com/docs/methods/analytics/get-analytics-data-breakdowns) Endpoint uses `startDate` and `endDate` in the query parameters instead of `start` and `end` which means that the date filter wont work.

API Docs:
![image](https://user-images.githubusercontent.com/6455850/220852879-a811cb34-a57e-4a42-9eac-da2caa839c2e.png)

BR

**Comment by ksvirkou-hubspot** [comment]
I've just fixed it in [the latest version](https://packagist.org/packages/hubspot/hubspot-php#5.1.0).
