### ISSUE TITLE
New Webhook Signatures

### ISSUE THREAD

**Issue by repat** [HubSpot/hubspot-php#403]
Hi,
in [this method](https://github.com/HubSpot/hubspot-php/blob/master/src/Utils/Webhooks.php#L16), this library is only validation `v1` Webhook requests. Could you update this to include v2 and v3 as laid out here: https://developers.hubspot.com/docs/api/webhooks/validating-requests

Thanks!

**Comment by ksvirkou-hubspot** [comment]
Hi @repat .
You can find all signatures in `SevenShores\Hubspot\Utils\Signature` ([link](https://github.com/HubSpot/hubspot-php/blob/v5.0.1/src/Utils/Signature.php)).

**Comment by ksvirkou-hubspot** [comment]
Workable example:
```php
Signature::isValid([
    'signature' => '9569219f8ba981ffa6f6f16aa0f48637d35d728c7e4d93d0d52efaa512af7900',
    'secret' => 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy',
    'requestBody' => '{"example_field":"example_value"}',
    'httpUri' => 'https://www.example.com/webhook_uri',
    'httpMethod' => 'POST',
    'signatureVersion' => 'v2',
]);
```
