### ISSUE TITLE
Hubspot Private app token ?

### ISSUE THREAD

**Issue by cycingguy** [HubSpot/hubspot-php#404]
Do you have anything in the works for Hubspots new private app token based auth?  Their replacement to API key?
https://app.hubspot.com/private-apps/9418140/1553569

Thanks!

**Comment by ksvirkou-hubspot** [comment]
Hi @cycingguy .
You can read read me about it in [README](https://github.com/HubSpot/hubspot-php#examples-using-factory).
```php
$hubspot = SevenShores\Hubspot\Factory::createWithOAuth2Token('access-token');
```
