### ISSUE TITLE
Symfony\Component\ErrorHandler\Error\FatalError with latest http-message PSR version

### ISSUE THREAD

**Issue by mx-jhinz** [HubSpot/hubspot-php#408]
We are having an issue with the latest the `hubspot/api-client` version v5.0.1 using the latest `guzzlehttp/guzzle` version 7.5.* and ` guzzlehttp/psr7` in version 2.5.* when using any package function (e.g. `vendor/hubspot/hubspot-php/src/Endpoints/EmailSubscription.php` >> `subscriptionStatus`):

We receive a PHP Fatal Error `Symfony\Component\ErrorHandler\Error\FatalError` - see following Stacktrace

```
Symfony\Component\ErrorHandler\Error\FatalError Declaration of SevenShores\Hubspot\Http\Response::getStatusCode() must be compatible with Psr\Http\Message\ResponseInterface::getStatusCode(): int 
    vendor/hubspot/hubspot-php/src/Http/Response.php:323 [main]
```

The package is incompatible with the latest `psr/http-message` package v2.0 which is included in `vendor/hubspot/hubspot-php/src/Http/Client.php`. The issue can be resolved by manually lock `psr/http-message` to version v1.1.

The client package does not explicitly require the `psr/http-message` package or the package in version 1.1 in the composer.json file. Please add this cross dependency to the composer.json and/or make the package compatible with the latest `psr/http-message` v2.0 version.

**Comment by zkingdesign** [comment]
Can anyone actually fix this? It's really annoying.

**Comment by ksvirkou-hubspot** [comment]
I am working on it.

**Comment by ksvirkou-hubspot** [comment]
I've just locked it in [the latest version](https://packagist.org/packages/hubspot/hubspot-php#5.1.0).
