### ISSUE TITLE
Library leaks API key when an error occurs

### ISSUE THREAD

**Issue by willemstuursma** [HubSpot/hubspot-php#88]
Whenever there is an HTTP or validation error at Hubspot, the library will throw a `GuzzleHttp\Exception\ClientException` with a message:

`Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: POST https://api.hubapi.com/contacts/v1/contact/createOrUpdate/email/orders@bliinq.com?hapikey=<redacted> resulted in a 400 Bad Request response: <redacted>`

This then gets picked up by our logging systems spreading the API key everywhere. 

I don't think the HTTP 4xx should result in a `GuzzleHttp\Exception\ClientException`, but a nice exception from this library which interprets the results from Hubspot and gives the domain exception message.

**Comment by maximejobin** [comment]
In the meantime, you could wrap your call in a try-catch. Then, simply do a `str_replace` to remove your key from the Exception a re-throw it. Not a fun thing to implement but that will do the job until it's officially fixed. 😃

**Comment by willemstuursma** [comment]
This issue celebrated its 2 year birthday the day before yesterday, I don't think security is important for Hubspot developers @ryanwinchester.

**Comment by maximejobin** [comment]
From my understanding, he is not working for HubSpot and is providing this library for free... when he has free time.

Feel free to submit a patch to the project to fix it.

**Comment by willemstuursma** [comment]
Ah I was not aware of that, will create a PR then.
