### ISSUE TITLE
Call fails when contact does not exists

### ISSUE THREAD

**Issue by fraincs** [HubSpot/hubspot-php#93]
e.g.
$contact = $hubspot->contacts()->getByEmail("test@hubspot.com");
returns an error
PHP Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.hubapi.com/contacts/v1/contact/email/test@hubspot.com/profile?hapikey=APIKEYNOTSHOWNHERE` resulted in a `404 Not Found` response:

Digging a bit in the source of my trouble and I think that having the ability to turn off 'http_errors' on $hubspot->contacts()->getByEmail would solve my problem but I don;t know if it is doable or an option

**Comment by gmaniac** [comment]
+1

**Comment by phena109** [comment]
Old trick of `try...catch` does the job for me

```
try {
    $result = $hs->contacts()->getByEmail($email);
} catch (BadRequest $exc) {
    if ($exc->getCode() == 404) {

    }
}
```

**Comment by dsoares** [comment]
What would be the expected behavior? 
From a previous commit (ebc8fb58), it was decided that Client::request would rethrow Guzzle exceptions (and not return a Response). So, i think @phena109 is right (not an old trick, it's the right way to do it, unless you change your thoughts about how hubspot-php should deal with Guzzle exceptions or 4xx / 5xx responses).

**Comment by mohammedanis** [comment]
This worked for me... In hubspot-php\src\Resources\Contacts.php, Line number 276 disable the http errors by replacing the line with this ['http_errors' => false],
Finally, It looks like this,
return $this->client->request(
    'get',
    $endpoint,
    ['http_errors' => false],
    build_query_string($params)
);

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
you can pass http_errors false and Guzzle won’t throw errors
```php
$hubspot = Factory::createWithOAuth2Token(
    'token', 
    null,
    ['http_errors' => false]
);
$response = $hubspot->contacts()->getByEmail("test@hubspot.com");
```
response
```
object(SevenShores\Hubspot\Http\Response)#18 (2) {
  ["data"]=>
  object(stdClass)#34 (5) {
    ["status"]=>
    string(5) "error"
    ["message"]=>
    string(22) "contact does not exist"
    ["correlationId"]=> ""
    ["errors"]=>
    array(1) {
      [0]=>
      object(stdClass)#35 (1) {
        ["message"]=>
        string(46) "The contact e:test@hubspot.com does not exist."
      }
    }
    ["category"]=>
    string(16) "OBJECT_NOT_FOUND"
  } ...
```
